name: todolist_motion
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  colorful_safe_area: ^1.0.0
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  logger: ^2.3.0
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
